import 'package:flutter/foundation.dart';

import 'member.dart';

//Widget build(BuildContext context) {
//  return Image(image: AssetImage('graphics/background.png'));
//}

class MemberList with ChangeNotifier {
  static final defaultImage = 'assets/images/Generic_Headshot_Man.jpg';

  // TODO: Creating data to load, not necessarily the Dart class structure.
  // TODO: Let's try auto generated keys for now.
  List<Member> _memberList = [
    Member(
      first: 'Pete',
      middle: '',
      last: 'Antos',
      suffix: '',
      address: '4 Bordeaux Lane',
      city: 'Beachwood',
      state: 'Ohio',
      zipCode: '44122',
      numOfPhones: 2,
      phones: {
        'number1': '216-509-3611',
        'name1': 'Home',
        'mobile1': true,
        'number2': '216-509-3611',
        'name2': 'Cell',
        'mobile2': true
      },
      birthday: DateTime(1962, 12, 14),
      emailHost: 'icloud.com',
      emailName: 'pistolpete766',
      imageUrl: defaultImage,
      joinedClub: null,
      deceasedDate: null,
      officer: null,
      groups: null,
      plusOneType: PlusOneType.GirlFriend,
      plusOneName: 'Candy',
      charterMember: false,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '002',
      first: 'Ken',
      last: 'Bell',
      address: '8330 Sheltered Cove',
      city: 'Mentor',
      state: 'Ohio',
      zipCode: '44060',
      phoneHome: '440-257-0119',
      phoneCell: '440-749-4461',
      phoneOther: null,
      birthday: DateTime(1963, 04, 16),
      charterMember: false,
      emailHost: 'dtgroup.net',
      emailName: 'kbell',
      plusOneType: 'W',
      plusOneName: 'Susan',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '003',
      first: 'Len',
      last: 'Busta',
      address: '692 Gold Leaf Ct',
      city: 'Streetsboro',
      state: 'Ohio',
      zipCode: '44136',
      phoneHome: '440-708-1145',
      phoneCell: '440-667-3868',
      phoneOther: null,
      birthday: DateTime(1954, 01, 05),
      charterMember: false,
      emailHost: 'windstream.net',
      emailName: 'bustamarilyn',
      plusOneType: 'W',
      plusOneName: 'Marilyn',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '004',
      first: 'Greg',
      last: 'Castillo Sr.',
      address: '27120 Fullerwood Drive',
      city: 'Euclid',
      state: 'Ohio',
      zipCode: '44132',
      phoneHome: '216-302-9993',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1949, 04, 03),
      charterMember: false,
      emailHost: 'core-tech-inc.com',
      emailName: 'greg',
      plusOneType: 'G',
      plusOneName: 'Laurie Koeth',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '005',
      first: 'Greg',
      last: 'Castillo Jr.',
      address: '10408 Plymouth Avenue',
      city: 'Garfield Heights',
      state: 'Ohio',
      zipCode: '44125',
      phoneHome: '440-241-3748',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1978, 12, 27),
      charterMember: false,
      emailHost: 'yahoo.com',
      emailName: 'rarebikes88',
      plusOneType: 'W',
      plusOneName: 'Tara',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '006',
      first: 'Joe',
      last: 'Castillo',
      address: '2806 Nottingham Drive',
      city: 'Parma',
      state: 'Ohio',
      zipCode: '44134',
      phoneHome: '216-702-1194',
      phoneCell: '216-702-1194',
      phoneOther: null,
      birthday: DateTime(1954, 09, 28),
      charterMember: false,
      emailHost: 'gianteagle.com',
      emailName: 'J.Castillo',
      plusOneType: 'W',
      plusOneName: 'Andrea',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '007',
      first: 'Chuck',
      last: 'Catalano',
      address: '8683 Jenna Drive',
      city: 'Broadview Heights',
      state: 'Ohio',
      zipCode: '44147',
      phoneHome: '440-546-1626',
      phoneCell: '440-465-6373',
      phoneOther: null,
      birthday: DateTime(1955, 05, 18),
      charterMember: false,
      emailHost: 'aol.com',
      emailName: 'fceichuck',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '008',
      first: 'Rich',
      last: 'Cesen',
      address: '38713 Chagrin Mills Court',
      city: 'Willoughby',
      state: 'Ohio',
      zipCode: '44094',
      phoneHome: '216-261-5391',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1936, 01, 12),
      charterMember: false,
      emailHost: '',
      emailName: '',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '009',
      first: 'Rick',
      last: 'Czerwinski',
      address: '815 Deepwoods Drive',
      city: 'Aurora',
      state: 'Ohio',
      zipCode: '44202',
      phoneHome: '330-995-3719',
      phoneCell: '216-536-0660',
      phoneOther: null,
      birthday: DateTime(1966, 06, 18),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'rickrjc21',
      plusOneType: 'W',
      plusOneName: 'Anne',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '010',
      first: 'Brian',
      last: 'Daley',
      address: '4117 Deer Run',
      city: 'Seven Hills',
      state: 'Ohio',
      zipCode: '44131',
      phoneHome: '216-256-7124',
      phoneCell: '216-256-7124',
      phoneOther: '216-236-3734',
      birthday: DateTime(1964, 06, 04),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'brian.daley',
      plusOneType: 'W',
      plusOneName: 'Marilyn',
      joinedClub: null,
      imageUrl: 'assets/images/Duke7.jpg',
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '011',
      first: 'Bob',
      last: 'Dombrowski',
      address: '8760 Webster Road',
      city: 'Strongsville',
      state: 'Ohio',
      zipCode: '44136',
      phoneHome: '440-572-0462',
      phoneCell: '440-668-9439',
      phoneOther: null,
      birthday: DateTime(1958, 07, 04),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'rwdbobbyd123',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '012',
      first: 'Dan',
      last: 'Ferguson',
      address: '14780 Watt Road ',
      city: 'Novelty',
      state: 'Ohio',
      zipCode: '44072',
      phoneHome: '440-821-0042',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1964, 09, 24),
      charterMember: false,
      emailHost: 'keithley.com',
      emailName: 'mferguson',
      plusOneType: 'W',
      plusOneName: 'Michelle',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '013',
      first: 'Doug',
      last: 'Ferguson',
      address: '9345 Apache Run',
      city: 'Macedonia',
      state: 'Ohio',
      zipCode: '44056',
      phoneHome: '216-970-3335',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1966, 09, 28),
      charterMember: false,
      emailHost: 'hotmail.com',
      emailName: 'dferguson911',
      plusOneType: 'W',
      plusOneName: 'Lynette',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '014',
      first: 'Matt',
      last: 'Findura',
      address: '738 Rachel Avenue',
      city: 'Brunswick',
      state: 'Ohio',
      zipCode: '44212',
      phoneHome: '216-310-9278',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1967, 07, 07),
      charterMember: false,
      emailHost: '',
      emailName: 'mfindUra@beveragedist.com',
      plusOneType: 'W',
      plusOneName: 'Sandy ',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '015',
      first: 'Joe',
      last: 'Fortuna',
      address: '680 East Pleasant Valley Road',
      city: 'Seven Hills',
      state: 'Ohio',
      zipCode: '44131',
      phoneHome: '216-702-5877',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1985, 03, 26),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'joseph.fortuna',
      plusOneType: 'W',
      plusOneName: 'Jennifer Jendre',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '016',
      first: 'John',
      last: 'Fortuna',
      address: '3985 East 42nd Street',
      city: 'Newburg Heights',
      state: 'Ohio',
      zipCode: '44105',
      phoneHome: '216-441-3598',
      phoneCell: '216-509-5017',
      phoneOther: null,
      birthday: DateTime(1957, 04, 07),
      charterMember: false,
      emailHost: 'att.net',
      emailName: 'John.fortuna',
      plusOneType: 'W',
      plusOneName: 'Roberta',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '017',
      first: 'Dave',
      last: 'Garee',
      address: '8372 Vera Drive ',
      city: 'Broadview Heights',
      state: 'Ohio',
      zipCode: '44117',
      phoneHome: ' 216-308-8013',
      phoneCell: '440.554.2935',
      phoneOther: null,
      birthday: DateTime(1959, 12, 20),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'davegaree',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '018',
      first: 'Ed',
      last: 'Globokar',
      address: '13502 Sherwood Circle',
      city: 'Garfield Heights',
      state: 'Ohio',
      zipCode: '44125',
      phoneHome: '216-581-7024',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1929, 01, 11),
      charterMember: true,
      emailHost: '',
      emailName: '',
      plusOneType: 'W',
      plusOneName: 'Evelyn',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '019',
      first: 'Joe',
      last: 'Globokar',
      address: '131 Pennsylvania Avenue',
      city: 'Louisville',
      state: 'Ohio',
      zipCode: '44641',
      phoneHome: '330-413- 6845',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1961, 01, 27),
      charterMember: false,
      emailHost: 'charakcenter.com',
      emailName: 'jglobokar',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '020',
      first: 'Mark',
      last: 'Globokar',
      address: '20265 Bradgate Lane',
      city: 'Strongsville',
      state: 'Ohio',
      zipCode: '44149',
      phoneHome: '440-878-8876',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1969, 01, 18),
      charterMember: false,
      emailHost: 'sbcglobal.net',
      emailName: 'lacmadness',
      plusOneType: 'W',
      plusOneName: 'Maryanne',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '021',
      first: 'Steve',
      last: 'Gwiazda',
      address: '8595 Broadview Road',
      city: 'Broadview Heights',
      state: 'Ohio',
      zipCode: '44147',
      phoneHome: '440-570-7269',
      phoneCell: '440-526-6877',
      phoneOther: null,
      birthday: DateTime(1971, 02, 01),
      charterMember: false,
      emailHost: 'yahoo.com',
      emailName: 'sgwiaz',
      plusOneType: 'W',
      plusOneName: 'Karen',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '022',
      first: 'Ryan',
      last: 'Helman',
      address: '5995 Ravine Boulevard',
      city: 'Parma',
      state: 'Ohio',
      zipCode: '44134',
      phoneHome: '216-870-4815',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1972, 04, 15),
      charterMember: false,
      emailHost: 'cox.net',
      emailName: 'helmanr',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '023',
      first: 'Darrell',
      last: 'Hibjan',
      address: '10261 Foxwood Drive',
      city: 'North Royalton',
      state: 'Ohio',
      zipCode: '44133',
      phoneHome: '440-237-0002',
      phoneCell: '216-346-5851',
      phoneOther: null,
      birthday: DateTime(1952, 10, 15),
      charterMember: false,
      emailHost: 'sbcglobal.net',
      emailName: 'darrell.hibjan',
      plusOneType: 'W',
      plusOneName: 'Ellen',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '024',
      first: 'Bobby',
      last: 'Hill',
      address: '3532 East 82nd Street',
      city: 'Cleveland',
      state: 'Ohio',
      zipCode: '44105',
      phoneHome: '216-883-6588',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1959, 08, 20),
      charterMember: false,
      emailHost: '',
      emailName: '',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '025',
      first: 'Neal',
      last: 'Hinz',
      address: '13437 Prescott Lane',
      city: 'strongsville',
      state: 'Ohio',
      zipCode: '44136',
      phoneHome: '440-799-5166',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1957, 10, 13),
      charterMember: false,
      emailHost: 'comcast.net',
      emailName: 'n.hinz',
      plusOneType: 'W',
      plusOneName: 'Brenda',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '026',
      first: 'Dean',
      last: 'Horba',
      address: '8921 Stephanie Drive',
      city: 'North Royalton',
      state: 'Ohio',
      zipCode: '44133',
      phoneHome: '216-299-7686',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1974, 10, 31),
      charterMember: false,
      emailHost: 'yahoo.com',
      emailName: 'dhorba74',
      plusOneType: 'W',
      plusOneName: 'Robin',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '027',
      first: 'Kris',
      last: 'Jones',
      address: '12146 Spruce Point',
      city: 'Strongsville',
      state: 'Ohio',
      zipCode: '44136',
      phoneHome: '440-915-6759',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1979, 02, 18),
      charterMember: false,
      emailHost: 'yahoo.com',
      emailName: 'joneskr218',
      plusOneType: 'W',
      plusOneName: 'Elizabeth',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '028',
      first: 'Thaddeus',
      last: 'Kastelic',
      address: '4617 West 149th Street',
      city: 'Cleveland',
      state: 'Ohio',
      zipCode: '44135',
      phoneHome: '216-671-5792',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1953, 02, 28),
      charterMember: false,
      emailHost: 'att.net',
      emailName: 'kastelic78',
      plusOneType: 'W',
      plusOneName: 'Julie',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '029',
      first: 'Tony',
      last: 'Kastelic',
      address: '440 Baldwin Drive',
      city: 'Howard',
      state: 'Ohio',
      zipCode: '43028',
      phoneHome: '740-393-4000',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1939, 10, 24),
      charterMember: false,
      emailHost: '',
      emailName: '',
      plusOneType: 'W',
      plusOneName: 'Rose',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '030',
      first: 'Tim',
      last: 'Klodnick',
      address: '6061 Millwood Drive',
      city: 'Broadview Heights',
      state: 'Ohio',
      zipCode: '44147',
      phoneHome: '440-526-6431',
      phoneCell: '440-567-4268',
      phoneOther: null,
      birthday: DateTime(1943, 03, 13),
      charterMember: false,
      emailHost: 'cox.net',
      emailName: 'tklodnick',
      plusOneType: 'W',
      plusOneName: 'Sherry',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '031',
      first: 'Bob',
      last: 'Kuznik',
      address: '7544 Pleasant Run Drive',
      city: 'Seven Hills',
      state: 'Ohio',
      zipCode: '44131',
      phoneHome: '216-447-4030',
      phoneCell: '216-509-9197',
      phoneOther: null,
      birthday: DateTime(1954, 09, 19),
      charterMember: false,
      emailHost: 'att.net',
      emailName: 'bobkuznik@gmail.com',
      plusOneType: 'W',
      plusOneName: 'Sue',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '032',
      first: 'Frank',
      last: 'Malec',
      address: '13981 Stonycreek Drive',
      city: 'North Royalton',
      state: 'Ohio',
      zipCode: '44133',
      phoneHome: '440-376-0487',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1956, 01, 21),
      charterMember: false,
      emailHost: 'fgmmedia.com ',
      emailName: 'frank',
      plusOneType: 'W',
      plusOneName: 'Wendy',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '033',
      first: 'Joe',
      last: 'Mannion',
      address: '10515 Laurel Lane',
      city: 'Brecksville',
      state: 'Ohio',
      zipCode: '44141',
      phoneHome: '440-546-1316',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1960, 01, 15),
      charterMember: false,
      emailHost: 'aol.com',
      emailName: 'brokenjoe',
      plusOneType: 'W',
      plusOneName: 'Kathy ',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '034',
      first: 'Tom',
      last: 'Mannion',
      address: '700 Timothy Lane ',
      city: 'Cleveland',
      state: 'Ohio',
      zipCode: '44109',
      phoneHome: '440-476-2729',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1958, 05, 27),
      charterMember: false,
      emailHost: 'aol.com',
      emailName: 'tomdgasman',
      plusOneType: 'W',
      plusOneName: 'Julie Ann',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '035',
      first: 'Tony',
      last: 'Mannion',
      address: '6645 Ivy Lane',
      city: 'Middleburg Heights',
      state: 'Ohio',
      zipCode: '44130',
      phoneHome: '440-591-0868',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1953, 08, 03),
      charterMember: false,
      emailHost: 'aol.com',
      emailName: 'tmannion47',
      plusOneType: 'W',
      plusOneName: 'Janice',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '036',
      first: 'Frank',
      last: 'Marincek',
      address: '628 Avon Drive',
      city: 'Aurora',
      state: 'Ohio',
      zipCode: '44202',
      phoneHome: '440-759-4736',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1956, 03, 11),
      charterMember: false,
      emailHost: 'yahoo.com',
      emailName: 'fhmgolf',
      plusOneType: 'W',
      plusOneName: 'Deanna',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '037',
      first: 'Nick',
      last: 'Mastronicolas',
      address: '4063 Magnolia Drive',
      city: 'Brunswick',
      state: 'Ohio',
      zipCode: '44212',
      phoneHome: '(216)973-1729 ',
      phoneCell: '(216)961-6300',
      phoneOther: null,
      birthday: DateTime(1959, 05, 17),
      charterMember: false,
      emailHost: 'msn.com',
      emailName: 'nickmastro59',
      plusOneType: 'W',
      plusOneName: 'Debbbie',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '038',
      first: 'Ryan',
      last: 'Mullally',
      address: '4861 South Park Ave',
      city: 'Fairview Park',
      state: 'Ohio',
      zipCode: '44126',
      phoneHome: '216-789-6517',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1980, 10, 03),
      charterMember: false,
      emailHost: 'hotmail.com',
      emailName: 'r_mullally',
      plusOneType: 'W',
      plusOneName: 'TODO',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '039',
      first: 'Dan',
      last: 'Murphy',
      address: '16860 Snyder Road ',
      city: 'Chagrin Falls',
      state: 'Ohio',
      zipCode: '44023',
      phoneHome: '',
      phoneCell: '440-318-5898',
      phoneOther: null,
      birthday: DateTime(1958, 10, 02),
      charterMember: false,
      emailHost: 'jonesday.com',
      emailName: 'dmmurphy',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '040',
      first: 'Nick',
      last: 'Musarra',
      address: '1252A Marks Road',
      city: 'Valley City ',
      state: 'Ohio',
      zipCode: '44280',
      phoneHome: '216-346-4057',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1981, 04, 19),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'nmusarra',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '041',
      first: 'Bob',
      last: 'Paluscsak',
      address: '8299 Springview',
      city: 'Sagamore Hills',
      state: 'Ohio',
      zipCode: '44067',
      phoneHome: '216-401-5698',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1966, 12, 05),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'bobop7701',
      plusOneType: 'W',
      plusOneName: 'Linda Jean',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '042',
      first: 'Ryan',
      last: 'Piontkowski',
      address: '8773 Mavis Trail ',
      city: 'Streetsboro',
      state: 'Ohio',
      zipCode: '44241',
      phoneHome: '216-702-2451',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1978, 06, 04),
      charterMember: false,
      emailHost: 'att.net ',
      emailName: 'piontkowski',
      plusOneType: 'W',
      plusOneName: 'Jessica ',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '043',
      first: 'Chuck',
      last: 'Potenga',
      address: '3232 Dales Court',
      city: 'North Royalton',
      state: 'Ohio',
      zipCode: '44133',
      phoneHome: '440-582-5169',
      phoneCell: '440-390-8552',
      phoneOther: null,
      birthday: DateTime(1955, 06, 27),
      charterMember: false,
      emailHost: 'wowway.com',
      emailName: 'cpotenga',
      plusOneType: 'W',
      plusOneName: 'Nancy',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '044',
      first: 'John',
      last: 'Rosco',
      address: '4247 Beck Road',
      city: 'Medina',
      state: 'Ohio',
      zipCode: '44256',
      phoneHome: '330-242-1004',
      phoneCell: '330-723-0303',
      phoneOther: null,
      birthday: DateTime(1970, 03, 20),
      charterMember: false,
      emailHost: 'ups.com',
      emailName: 'Jrosco',
      plusOneType: 'W',
      plusOneName: 'Monica',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '045',
      first: 'Ken',
      last: 'Salacienski',
      address: '10180 Prouty Road',
      city: 'Concord Township',
      state: 'Ohio',
      zipCode: '44077',
      phoneHome: '440-343-2047',
      phoneCell: '440-352-0924',
      phoneOther: null,
      birthday: DateTime(1959, 05, 20),
      charterMember: false,
      emailHost: 'sbcglobal.net',
      emailName: 'ksalacienski',
      plusOneType: 'W',
      plusOneName: 'Cindy',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '046',
      first: 'Wally',
      last: 'Sarnowski',
      address: '6673 Forestwood Street Northwest',
      city: 'Canton',
      state: 'Ohio',
      zipCode: '44718',
      phoneHome: '330-417-6793',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1981, 08, 04),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'wallsarn',
      plusOneType: 'W',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '047',
      first: 'Marc',
      last: 'Seifried ',
      address: '18010 Birch Hill Drive',
      city: 'Chagrin Falls',
      state: 'Ohio',
      zipCode: '44023',
      phoneHome: '440-840-5816',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1977, 06, 11),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'markm1010',
      plusOneType: 'W',
      plusOneName: 'Katie',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '048',
      first: 'Dave',
      last: 'Skrajner',
      address: '38713 Chagrin Mills Court',
      city: 'Willoughby',
      state: 'Ohio',
      zipCode: '44094',
      phoneHome: '440-953-8302',
      phoneCell: '216-401-8817',
      phoneOther: null,
      birthday: DateTime(1954, 02, 24),
      charterMember: false,
      emailHost: '',
      emailName: 'skrajnerd@gmail.com',
      plusOneType: 'W',
      plusOneName: 'Kathy',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '049',
      first: 'Jim',
      last: 'Skufca',
      address: '8477 Westport Drive',
      city: 'Mentor',
      state: 'Ohio',
      zipCode: '44060',
      phoneHome: '440-205-3677',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1930, 10, 30),
      charterMember: true,
      emailHost: 'fasinv.com',
      emailName: 'Skufca169@gmail.com',
      plusOneType: 'W',
      plusOneName: 'Eileen',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '050',
      first: 'Jim',
      last: 'Skufca Jr.',
      address: '8366 Canterbury Court',
      city: 'Chagrin Falls',
      state: 'Ohio',
      zipCode: '44023',
      phoneHome: '440-543-0689',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1966, 03, 07),
      charterMember: false,
      emailHost: 'curtisswright.com',
      emailName: 'jskufca',
      plusOneType: 'W',
      plusOneName: 'Jill',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '051',
      first: 'Greg',
      last: 'Specht',
      address: '215 East Decker Drive ',
      city: 'Seven Hills',
      state: 'Ohio',
      zipCode: '44131',
      phoneHome: '216-407-9068',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1963, 02, 08),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'gmspecht',
      plusOneType: 'W',
      plusOneName: 'Libbie',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '052',
      first: 'Frank',
      last: 'Strainer',
      address: '709 Elmwood Point',
      city: 'Aurora',
      state: 'Ohio',
      zipCode: '44202',
      phoneHome: '330-348-0447',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1937, 06, 28),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'fdstrainer1958',
      plusOneType: 'W',
      plusOneName: 'Donna',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: true,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '053',
      first: 'Jerry',
      last: 'Strainer',
      address: '313 Charring Cross Drive',
      city: 'Munroe Falls',
      state: 'Ohio',
      zipCode: '44262',
      phoneHome: '330-688-2470',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1940, 10, 06),
      charterMember: false,
      emailHost: '',
      emailName: '',
      plusOneType: 'W',
      plusOneName: 'Jane',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '054',
      first: 'Jon',
      last: 'Strainer',
      address: '4081 Bassett Road',
      city: 'Atwater',
      state: 'Ohio',
      zipCode: '44201',
      phoneHome: '330-253-1164',
      phoneCell: '330-573-7859',
      phoneOther: null,
      birthday: DateTime(1969, 11, 21),
      charterMember: false,
      emailHost: 'aol.com',
      emailName: 'jjs1093',
      plusOneType: 'G',
      plusOneName: 'Chrissy Bhanton',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '055',
      first: 'Bob',
      last: 'Strazar',
      address: '648 Sandra Drive',
      city: 'Brunswick',
      state: 'Ohio',
      zipCode: '44212',
      phoneHome: '216-571-5575',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1960, 03, 10),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'bstrazar',
      plusOneType: 'W',
      plusOneName: 'Linda',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '056',
      first: 'Ray',
      last: 'Strazar',
      address: '1653 Arash Circle',
      city: 'Port Orange',
      state: 'Florida',
      zipCode: '32128',
      phoneHome: '386-304-5166',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1930, 12, 06),
      charterMember: true,
      emailHost: '',
      emailName: '',
      plusOneType: 'W',
      plusOneName: 'Arlene',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '057',
      first: 'Ron',
      last: 'Strazar',
      address: '317 Wilson Mills Road',
      city: 'Chardon',
      state: 'Ohio',
      zipCode: '44024',
      phoneHome: '440-214-5653',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1964, 10, 20),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'ronaldstrazar',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: 'assets/images/Ron_Strazar.jpeg',
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '058',
      first: 'Craig',
      last: 'Supan',
      address: '5968 Forest Ridge Drive',
      city: 'North Olmstead',
      state: 'Ohio',
      zipCode: '44070',
      phoneHome: '216-870-7401',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1982, 11, 07),
      charterMember: false,
      emailHost: 'gmail.com',
      emailName: 'craig.supan',
      plusOneType: 'W',
      plusOneName: 'Beth',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '059',
      first: 'Dean',
      last: 'Supan',
      address: '831 Wildwood Court',
      city: 'Medina',
      state: 'Ohio',
      zipCode: '44256',
      phoneHome: '330-754-7838',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1960, 04, 25),
      charterMember: false,
      emailHost: 'zoominternet.net',
      emailName: 'dsupan7',
      plusOneType: 'W',
      plusOneName: 'Diane',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '060',
      first: 'Gery',
      last: 'Trepczyk',
      address: '1590 Jo Ann Drive',
      city: 'Parma',
      state: 'Ohio',
      zipCode: '44134',
      phoneHome: '440-785-4796',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1966, 05, 13),
      charterMember: false,
      emailHost: 'yahoo.com',
      emailName: 'GeryTrep',
      plusOneType: 'W',
      plusOneName: 'Michelle',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '061',
      first: 'William',
      last: 'Urban',
      address: '3986 East 52nd Street',
      city: 'Newburg Heights',
      state: 'Ohio',
      zipCode: '44105',
      phoneHome: '216-641-0164',
      phoneCell: '216 598 0266',
      phoneOther: null,
      birthday: DateTime(1953, 05, 08),
      charterMember: false,
      emailHost: 'hotmail.com',
      emailName: 'willis503',
      plusOneType: 'N',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '062',
      first: 'Tyler',
      last: 'Waryk',
      address: '6304 E Sprague Road',
      city: 'Broadview Hts.',
      state: 'Ohio',
      zipCode: '44147',
      phoneHome: '216-618-4758',
      phoneCell: null,
      phoneOther: null,
      birthday: DateTime(1993, 05, 14),
      charterMember: false,
      emailHost: 'waryk.com',
      emailName: 'tyler',
      plusOneType: 'W',
      plusOneName: 'Nicolette',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '063',
      first: 'Bill',
      last: 'Wingler',
      address: '',
      city: '',
      state: '',
      zipCode: '',
      phoneHome: '',
      phoneCell: '',
      phoneOther: null,
      birthday: null,
      charterMember: false,
      emailHost: '',
      emailName: '',
      plusOneType: '',
      plusOneName: '',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: false,
      probationaryMember: true,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '063',
      first: 'Dan',
      last: 'Wojtila',
      address: '7680 Marewood Place',
      city: 'Painesville',
      state: 'Ohio',
      zipCode: '44077',
      phoneHome: '216-701-0769',
      phoneCell: '440-853-8088',
      phoneOther: null,
      birthday: DateTime(1953, 09, 27),
      charterMember: false,
      emailHost: 'hotmail.com',
      emailName: 'fire5cpa',
      plusOneType: 'W',
      plusOneName: 'Janice',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
    Member(
      id: '064',
      first: 'Joe',
      last: 'Wojtila',
      address: '3111 Elisha Lane',
      city: 'Twinsburg',
      state: 'Ohio',
      zipCode: '44087',
      phoneHome: '330-963-2929',
      phoneCell: '440-487-0118',
      phoneOther: null,
      birthday: DateTime(1956, 03, 02),
      charterMember: false,
      emailHost: 'roadrunner.com',
      emailName: 'jdwojo',
      plusOneType: 'W',
      plusOneName: 'Delene',
      joinedClub: null,
      imageUrl: defaultImage,
      deceased: false,
      fullMember: true,
      probationaryMember: false,
      over72Member: false,
      mailedNewsLetter: false,
      associateMember: false,
    ),
  ];

  List<Member> get members {
    return [..._memberList];
  }

  List<Member> get favoriteItems {
    var list = _memberList.where((prodItem) => prodItem.favorite).toList();
    return list != null ? list : [];
  }

  List<Member> get activeItems {
    var list = _memberList.where((prodItem) => !prodItem.deceased).toList();
    return list != null ? list : [];
  }

  List<Member> memberWithBirthdaysThisMonth() {
    final nowMonth = DateTime.now().month;
    var list = _memberList
        .where((prodItem) =>
            (prodItem.birthday != null ? prodItem.birthday.month : -1) ==
            nowMonth)
        .toList();
    list.sort((a, b) => a.birthday.compareTo(b.birthday));
    return list != null ? list : [];
  }
}
